export const images = {
  MANIFEST: "/manifest.json",
  DEFAULTS: {
    COVER: "/defaults/default-cover.svg",
  },
  LOGOS: {
    DEFAULT: "/logos/logo.png",
    DARK: "/logos/logo-dark.png",
    BETA: "/logos/logo-beta.png",
    BETA_ALT: "/logos/beta-logo.png",
  },
  ICONS: {
    DEFAULT: "/icons/icon.png",
    DARK: "/icons/icon-dark.png",
    BETA: "/icons/icon-beta.png",
    BETA_192: "/icons/icon-beta-192.png",
    BETA_512: "/icons/icon-beta-512.png",
    PWA_192: "/icons/pwa-192.png",
    PWA_512: "/icons/pwa-512.png",
  },
  LANDING: {
    HERO: "/landing/landing.png",
    ECOSYSTEM: "/landing/ecosystem.svg",
    LAMP: "/landing/lamp.svg",
    OPTIONS: "/landing/options.svg",
    PEOPLE: "/landing/people.svg",
    INAPI: "/landing/inapi.png",
    INAPI_LOGO: "/landing/inapi-logo.png",
    GOLANG: "/landing/golang.png",
    GOLANG_LOGO: "/landing/golang-logo.png",
  },
  ILLUSTRATIONS: {
    EMPTY: "/images/empty.png",
    ERROR: "/images/error.svg",
    INSTALL_PWA: "/images/install-pwa.png",
    TODO: "/images/todo.png",
  },
  BADGES: {
    VERIFIED: "/badges/verified.png",
    NOTTER: "/badges/notter.png",
    NOTE_VERIFIED: "/badges/note-verified.png",
    ORG_VERIFIED: "/badges/org-verified.png",
    MODERATOR: "/badges/moderator.png",
    CONTRIBUTOR: "/badges/contributor.png",
    AMBER: "/badges/amber.png",
    DIAMOND: "/badges/diamond.png",
    RUBY: "/badges/ruby.png",
    ID: "/badges/id.png",
  },
} as const;
